-- DO NOT MODIFY THIS FILE MANUALLY
-- This file is generated by running the configure script.
local stackables = {}

-- Defined itemss
stackables.items = {
    {
        ["item-name"] = "omnine",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-omnine.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnine-shards",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-omnine-shards.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "shattered-omnine",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-shattered-omnine.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "quasi-solid-omnistal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-quasi-solid-omnistal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "oscillocrystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-oscillocrystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnilgium",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-omnilgium.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "electrocrystal",
        ["unlock-tier"] = "deadlock-stacking-3",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-electrocrystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "impure-crystal-rod",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-impure-crystal-rod.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "crystal-rod",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-crystal-rod.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "iron-ore-omnide-salt",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-iron-ore-omnide-salt.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {
            {
                ["icon"] = "__base__/graphics/icons/iron-ore.png",
                ["icon_size"] = 64,
                ["scale"] = 0.21875,
                ["shift"] = {-10, 10}
            }
        }
    },
    {
        ["item-name"] = "fragmented-iron-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-fragmented-iron-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "iron-ore-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-iron-ore-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "copper-ore-omnide-salt",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-copper-ore-omnide-salt.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {
            {
                ["icon"] = "__base__/graphics/icons/copper-ore.png",
                ["icon_size"] = 64,
                ["scale"] = 0.21875,
                ["shift"] = {-10, 10}
            }
        }
    },
    {
        ["item-name"] = "fragmented-copper-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-fragmented-copper-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "copper-ore-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-copper-ore-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "uranium-ore-omnide-salt",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-uranium-ore-omnide-salt.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {
            {
                ["icon"] = "__base__/graphics/icons/uranium-ore.png",
                ["icon_size"] = 64,
                ["scale"] = 0.21875,
                ["shift"] = {-10, 10}
            }
        }
    },
    {
        ["item-name"] = "uranium-ore-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-uranium-ore-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnine-structure-crystal",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-omnine-structure-crystal.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "basic-crystallonic",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-basic-crystallonic.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "basic-oscillo-crystallonic",
        ["unlock-tier"] = "deadlock-stacking-3",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_crystal/stacked-basic-oscillo-crystallonic.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    }
}

-- Defined fluidss
stackables.fluids = {}

return stackables
