-- DO NOT MODIFY THIS FILE MANUALLY
-- This file is generated by running the configure script.
local stackables = {}

-- Defined itemss
stackables.items = {
    {
        ["item-name"] = "omniwood",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter_wood/stacked-omniwood.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    }
}

-- Defined fluidss
stackables.fluids = {}

return stackables
