-- DO NOT MODIFY THIS FILE MANUALLY
-- This file is generated by running the configure script.
local stackables = {}

-- Defined itemss
stackables.items = {
    {
        ["item-name"] = "omnite",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnite.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "stone-crushed",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-stone-crushed.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "pulverized-stone",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-pulverized-stone.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "crushed-omnite",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-crushed-omnite.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "pulverized-omnite",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-pulverized-omnite.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnite-brick",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnite-brick.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnicium-plate",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnicium-plate.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnicium-iron-alloy",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnicium-iron-alloy.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {
            {
                ["icon"] = "__base__/graphics/icons/iron-plate.png",
                ["icon_size"] = 64,
                ["scale"] = 0.21875,
                ["shift"] = {-10, 10}
            }
        }
    },
    {
        ["item-name"] = "omnicium-steel-alloy",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnicium-steel-alloy.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {
            {
                ["icon"] = "__base__/graphics/icons/steel-plate.png",
                ["icon_size"] = 64,
                ["scale"] = 0.21875,
                ["shift"] = {-10, 10}
            }
        }
    },
    {
        ["item-name"] = "omnicium-gear-wheel",
        ["unlock-tier"] = "deadlock-stacking-1",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnicium-gear-wheel.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    },
    {
        ["item-name"] = "omnicium-iron-gear-box",
        ["unlock-tier"] = "deadlock-stacking-2",
        ["icon"] = "__DeadlockStackingForOmnimatter__/graphics/icons/omnimatter/stacked-omnicium-iron-gear-box.png",
        ["icon-size"] = 64,
        ["icon-additions"] = {}
    }
}

-- Defined fluidss
stackables.fluids = {}

return stackables
